# --- Pin & Port Configuration (BCM numbering) ---
# Stepper Motor Pins
STEPPER_PINS = {
    'DIR': 26,
    'STEP': 13,
    'ENABLE': 23,
    'RESET': 19,
    'M0': 0,
    'M1': 5,
    'M2': 6
}

# Servo Motor Pin
SERVO_PIN = 2

# LiDAR Serial Port (GPIO 14/15 -> /dev/ttyS0)
LIDAR_SERIAL_PORT = '/dev/ttyS0'
LIDAR_BAUD_RATE = 115200

# --- Motor & Movement Settings ---
STEPS_PER_REVOLUTION = 6400
STEPPER_PULSE_DELAY = 0.0001
SERVO_MIN_PULSE = 500
SERVO_MAX_PULSE = 2500
SERVO_UPDATE_INTERVAL = 0.01

# --- Stepper and Servo Sweep Settings ---
STEPPER_SWEEP_DEGREES = 40
SERVO_SWEEP_START = 5
SERVO_SWEEP_END = 25

# --- Calibration & Detection Settings ---
CALIBRATION_SWEEPS = 2
DETECTION_THRESHOLD_FACTOR = 0.8
DETECTION_CONFIDENCE_THRESHOLD = 5
TOTAL_DETECTIONS_TO_FIND = 3

# --- Advanced Scan Settings ---
ASSURANCE_STEPPER_SWEEP = 20
TRAJECTORY_STEPPER_SWEEP = 10
TRAJECTORY_SERVO_STEP = 1.5
UPDATE_THRESHOLD = 5
